### ISSUE TITLE
Deprecate `Bundle`

### ISSUE THREAD

**Issue by torkleyy** [amethyst/specs#482]
`Bundle` is hardly a useful or necessary trait and I don't see any point in maintaining it. As was pointed out in [an IRC chat](https://botbot.me/mozilla/rust-gamedev/2018-09-10/?tz=America/Los_Angeles), there already is a trait for this: `Fn(World)`.

**Comment by Xaeroxe** [comment]
To be more precise: `FnOnce(&mut World)`.  But yeah

**Comment by Aceeri** [comment]
It also would probably just be generally better for libraries to provide a `setup` method of their own rather than us trying to bring all those dependencies together.

**Comment by torkleyy** [comment]
A clarification in the book would be nice.

**Comment by ldesgoui** [comment]
I can cook something up for the setup chapter today-ish

I've noticed that all(?) examples don't call `Dispatcher.setup()` meaning the Resources/Components they require are not registered automatically. As far as I can tell, that's possibly because `main()` always creates a few entities before running the dispatcher, but that could be fixed by having `Dispatcher.setup()` before creating entities, then running it afterwards. This would remove the need to register components and resources.
As for registering systems in bulk, it was mentioned that a simple standalone function would do the job, and libraries could implement their own trait if they so desire

**Comment by torkleyy** [comment]
Yes, exactly :+1: A PR to add this to the book would be tops!

**Comment by ldesgoui** [comment]
I believe this can be closed now :)
